name: Auto Update Configs

on:
  schedule:
    # Runs every 4 hours (00:00, 04:00, 08:00, etc.)
    - cron: '0 */4 * * *'
  workflow_dispatch: # Allows you to manually click "Run" button

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Aggregator Script
        run: python main.py

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "🚀 Auto-update configs [$(date)]" || exit 0
          git push